import { Navbar, Sidebar, Todos } from "@/components";
import { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";

import { AnimatePresence } from "framer-motion";

const Index: NextPage = () => {
  const [sidebarOpen, setSidebarOpen] = useState<boolean>(false);
  const [width, setWidth] = useState(
    typeof window !== "undefined" && window.innerWidth
  );

  const updateDimensions = () => {
    setWidth(typeof window !== "undefined" && window.innerWidth);
  };

  useEffect(() => {
    window.addEventListener("resize", updateDimensions);
    return () => window.removeEventListener("resize", updateDimensions);
  }, []);

  useEffect(() => {
    if (Number(width) < 950 && sidebarOpen) {
      setSidebarOpen(false);
    }
  }, [width]);

  return (
    <>
      <Head>
        <title>MY NOTES</title>
        <meta name="description" content="Generated by love" />
      </Head>
      <Navbar setOpenSideBar={() => setSidebarOpen(!sidebarOpen)} />
      <div className="relative md:flex">
        <AnimatePresence>{sidebarOpen && <Sidebar />}</AnimatePresence>
        <Todos />
      </div>
    </>
  );
};

export default Index;
